# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ca770848d753555cdf680d80b6d36eb9a55c0bfdc7fd6f1631a91e78fdbbbd930560d302eed229f2a19cec022836151c7d1efb5207d68bb2d3be3bfb3d5a095

test:
  secret_key_base: b50c609f9937ac6c0f834b19e8830a7325e0f33ca8904d98e93c2d2a57ea53eb129fc98273fff0300040550a3725578fb7553c0b0e0b229120bcac2469b42513

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
